server:
  port: 9085

spring:
  application:
    name: ms-gateway-server

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

      routes:
        - id: ms-cuartos
          uri: lb://ms-cuartos
          predicates:
            - Path=/rooms/**
          filters:
            - name: AuthFilter

        - id: ms-reservas
          uri: lb://ms-reservas
          predicates:
            - Path=/reservations/**
          filters:
            - name: AuthFilter

        - id: ms-estudiantes
          uri: lb://ms-estudiantes
          predicates:
            - Path=/students/**
          filters:
            - name: AuthFilter

        - id: ms-auth-service
          uri: lb://ms-auth-service
          predicates:
            - Path=/auth/**

      # 💡 Configuración global de CORS
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:4200"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8085/eureka}
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
